# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatTransectsDialog(object):
    def setupUi(self, BatTransectsDialog):
        BatTransectsDialog.setObjectName("BatTransectsDialog")
        BatTransectsDialog.resize(320, 160)
        self.verticalLayout = QtWidgets.QVBoxLayout(BatTransectsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelLayer = QtWidgets.QLabel(BatTransectsDialog)
        self.labelLayer.setObjectName("labelLayer")
        self.verticalLayout.addWidget(self.labelLayer)
        self.layerComboBox = QtWidgets.QComboBox(BatTransectsDialog)
        self.layerComboBox.setObjectName("layerComboBox")
        self.verticalLayout.addWidget(self.layerComboBox)
        self.labelBuffer = QtWidgets.QLabel(BatTransectsDialog)
        self.labelBuffer.setObjectName("labelBuffer")
        self.verticalLayout.addWidget(self.labelBuffer)
        self.bufferLineEdit = QtWidgets.QLineEdit(BatTransectsDialog)
        self.bufferLineEdit.setObjectName("bufferLineEdit")
        self.verticalLayout.addWidget(self.bufferLineEdit)
        self.generateButton = QtWidgets.QPushButton(BatTransectsDialog)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayout.addWidget(self.generateButton)

        self.retranslateUi(BatTransectsDialog)
        QtCore.QMetaObject.connectSlotsByName(BatTransectsDialog)

    def retranslateUi(self, BatTransectsDialog):
        _translate = QtCore.QCoreApplication.translate
        BatTransectsDialog.setWindowTitle(_translate("BatTransectsDialog", "Bat Transects"))
        self.labelLayer.setText(_translate("BatTransectsDialog", "Wybierz warstwę punktową:"))
        self.labelBuffer.setText(_translate("BatTransectsDialog", "Promień bufora (m):"))
        self.generateButton.setText(_translate("BatTransectsDialog", "Generuj transekty"))
